export const seoKeywords = [
  "Joshua Onyenwere",
  "Web Developer",
  "Web Designer",
  "Portfolio",
  "Fullstack developer",
  "Fullstack web developer",
  "Frontend developer",
  "Backend developer",
  "PHP developer",
  "Laravel developer",
  "JavaScript developer",
  "TypeScript developer",
  "Python developer",
  "Django developer",
  "React developer",
  "Vue.js developer",
  "Nest.js developer",
  "Next.js developer",
  "Node.js developer",
  "MongoDB developer",
  "MERN stack developer",
  "Software developer",
  "Software engineer",
  "Web developer in Germany",
  "Web developer in München",
];
